### PR TITLE
Use Leaflet's events rather than callback options

### PR DESCRIPTION
**Pull request by jfirebaugh**
Leaflet has a built-in [event system](http://leaflet.cloudmade.com/reference.html#events). It would be more consistent with built-in Leaflet controls and other plugins to expose the change/enabled/disabled events using that API rather than the current onChange/onEnabled/onDisabled options. It would also be more flexible (for example, it would allow multiple callbacks to be bound to an event).

### CODE REVIEW

**Comment by kajic** [comment]
Yeah, I agree the leaflet event system would be better. I will make the changes when I have time. Feel free to do it if you feel inspired :)

**Comment by jfirebaugh** [comment]
Yeah, I will work on it. :)

**Comment by jfirebaugh** [comment]
Converted to pull request.

**Comment by kajic** [comment]
If I am not misstaken your idea is for event listeners to call getBounds() (if they want to) when they are triggered. But since I think every event listener will almost always want to do this, I wonder if it's not better if the bounds objects is passed along to them when fire() is called. This way they don't need to call getBounds() themselves.

**Comment by jfirebaugh** [comment]
The event object's `target` will be set to the location filter. So the difference would be between `e.target.getBounds()` and `e.bounds`. I think `e.bounds` makes sense for the `change` event but not for the other events.

**Comment by kajic** [comment]
Oh, I actually thought the object would be given to the callback as an extra argument. 
Anyway, I see how e.bounds is weird for something like adjustToZoomClick, but I think the enabled event should have it. In many applications it will probably need to do everything that is done when change is triggered, plus some additional initialization. 
I'll merge this for now.

**Pull request merged**
